permalink: /:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true
markdown: kramdown

url: http://ronnqvi.st

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : David Rönnqvist
author :
  name : Name Lastname
  github : d-ronnqvist
  twitter : davidronnqvist

production_url : http://ronnqvi.st

  
